sudo: false
language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - libopenblas-base
      - libopenblas-dev
      - liblapack-dev
      - gfortran  
before_install:
  - pip install --upgrade pip
  - pip install pytest pytest-cov
  - pip install coveralls
install: 
  - pip install nutsml
script:
  - "echo 'backend : Agg' > matplotlibrc"
  - py.test
  - coverage run --source=nutsml setup.py test
after_success:
  - coveralls  
