sudo: false
language: python
python:
  - "2.7"
cache: pip
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install: 
  - pip install nutsml
script: 
  - py.test
after_success:
  - coveralls  
