sudo: false
language: python
python:
  - "2.7"
  - "3.6"
addons:
  apt:
    packages:
      - libopenblas-base
      - libopenblas-dev
      - liblapack-dev
      - gfortran  
before_install:
  - pip install --upgrade pip
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install six
  - pip install pyyaml
  - pip install xlrd
  - pip install dplython
  - pip install numpy
  - pip install matplotlib
  - pip install scipy
  - pip install pillow
  - pip install scikit-image
  - pip install pandas 
install: 
  - pip install nutsml
script:
  - "echo 'backend : Agg' > matplotlibrc"
  - py.test
  - coverage run --source=nutsml --omit="nutsml/examples/*" setup.py test 
after_success:
  - coveralls  
